#!/bin/bash

export MAINFOLDER=`pwd`

if [ "" = "$1" ]; 
then
	echo "Enter build target directory."
	exit 1
fi

if [ "" = "${NDK}" ]; 
then
	echo "NDK Path is empty."
	exit 1
fi

if [ ! -d $1 ]; 
then
	mkdir "$1"
fi

#
cd "$1" #>/dev/null 2>&1 && 

if [ "debug" = "$2" ];
then
cmake "$MAINFOLDER" -G "Unix Makefiles" -DOGRE_BUILD_PLATFORM_ANDROID=1 -DOGREKIT_UNITY_BUILD=1 -DOGRE_UNITY_BUILD=1 -DOGREKIT_MINIMAL_FREEIMAGE_CODEC=1 -DOGREKIT_BUILD_ANDROID=1 -DCMAKE_TOOLCHAIN_FILE="$MAINFOLDER/SDK/Android/android-r5b.toolchain" --debug-trycompile && \
cmake "$MAINFOLDER" -G "Unix Makefiles" -DOGRE_BUILD_PLATFORM_ANDROID=1 -DOGREKIT_UNITY_BUILD=1 -DOGRE_UNITY_BUILD=1 -DOGREKIT_MINIMAL_FREEIMAGE_CODEC=1 -DOGREKIT_BUILD_ANDROID=1 -DCMAKE_TOOLCHAIN_FILE="$MAINFOLDER/SDK/Android/android-r5b.toolchain" --debug-trycompile
else
cmake "$MAINFOLDER" -G "Unix Makefiles" -DOGRE_BUILD_PLATFORM_ANDROID=1 -DOGREKIT_UNITY_BUILD=1 -DOGRE_UNITY_BUILD=1 -DOGREKIT_MINIMAL_FREEIMAGE_CODEC=1 -DOGREKIT_BUILD_ANDROID=1 -DCMAKE_TOOLCHAIN_FILE="$MAINFOLDER/SDK/Android/android-r5b.toolchain" -DCMAKE_BUILD_TYPE="MinSizeRel" && \
cmake "$MAINFOLDER" -G "Unix Makefiles" -DOGRE_BUILD_PLATFORM_ANDROID=1 -DOGREKIT_UNITY_BUILD=1 -DOGRE_UNITY_BUILD=1 -DOGREKIT_MINIMAL_FREEIMAGE_CODEC=1 -DOGREKIT_BUILD_ANDROID=1 -DCMAKE_TOOLCHAIN_FILE="$MAINFOLDER/SDK/Android/android-r5b.toolchain" -DCMAKE_BUILD_TYPE="MinSizeRel"
fi

# make
