/*
-------------------------------------------------------------------------------
	This file is part of OgreKit.
	http://gamekit.googlecode.com/

	Copyright (c) 2009 Charlie C.
-------------------------------------------------------------------------------
 This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
	 claim that you wrote the original software. If you use this software
	 in a product, an acknowledgment in the product documentation would be
	 appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
	 misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.
-------------------------------------------------------------------------------
*/
#ifndef _OgreBlendConverter_h_
#define _OgreBlendConverter_h_

#include "OgrePrerequisites.h"
#include "autogenerated/blender.h"
#include "OgreUtilsAllocator.h"
#include "OgreHashTable.h"
#include "OgreList.h"

namespace bParse {
	class bBlenderFile;
}


namespace Ogre 
{


class BlendConverter : public AllocObject
{
public:
    typedef List<ManualResourceLoader*> ManualLoaderList;
	typedef HashTable<Blender::Image*, Texture*> ImageMap;

protected:
    ManualLoaderList		m_loaders;
	bParse::bBlenderFile*	m_file;
	String					m_group;
	ImageMap				m_images;

public:

	BlendConverter(bParse::bBlenderFile* file, const String& group);
    ~BlendConverter();

	void registerImage(Blender::Image *ima);
	Mesh *createManualMesh(Blender::Object *ob);
	Skeleton *createManualSkeleton(Blender::Object *ob);

	OGRE_INLINE bParse::bBlenderFile *getInternalFile(void){return m_file;}

};

}

#endif//_OgreBlendConverter_h_
