/*
-------------------------------------------------------------------------------
	This file is part of the Ogre GameKit port.
	http://gamekit.googlecode.com/

	Copyright (c) 2009 Charlie C.
-------------------------------------------------------------------------------
 This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
	 claim that you wrote the original software. If you use this software
	 in a product, an acknowledgment in the product documentation would be
	 appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
	 misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.
-------------------------------------------------------------------------------
*/
#ifndef _OgreLoaderUtils_h_
#define _OgreLoaderUtils_h_


#include "OgreLoaderCommon.h"
#include "OgreBlendConverter.h"
#include "autogenerated/blender_Common.h" // forwards


namespace Ogre {

//-----------------------------------------------------------------------------
class LoaderUtils
{
public:
	LoaderUtils(bParse::bBlenderFile *file);
	Blender::Material* getMaterial(Blender::Object *ob, int index);
	void getLayers(Blender::Mesh *mesh, Blender::MTFace **eightLayerArray, Blender::MCol **oneMCol, int &validLayers);

	// animation / skeleton utils
	int getDeformGroupIndex(Blender::Object *ob, const char *group);

private:
	bParse::bBlenderFile *m_file;
};


}


#endif//_OgreLoaderUtils_h_
