/*
-------------------------------------------------------------------------------
	This file is part of the Ogre GameKit port.
	http://gamekit.googlecode.com/

	Copyright (c) 2009 Charlie C.
-------------------------------------------------------------------------------
 This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
	 claim that you wrote the original software. If you use this software
	 in a product, an acknowledgment in the product documentation would be
	 appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
	 misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.
-------------------------------------------------------------------------------
*/
#ifndef _OgreSkeletonLoader_h_
#define _OgreSkeletonLoader_h_


#include "OgreBlendConverter.h"
#include "OgreString.h"
#include "OgreResource.h"
#include "OgreResourceManager.h"
#include "OgrePrerequisites.h"
#include "OgreMatrix4.h"
#include "autogenerated/blender_Common.h"

namespace Ogre {

//-----------------------------------------------------------------------------
class SkeletonLoaderPrivate;


//-----------------------------------------------------------------------------
class SkeletonLoader : public ManualResourceLoader
{
public:
	SkeletonLoader(BlendConverter *fp, Blender::Object *arma);
	virtual ~SkeletonLoader();

	void loadResource(Resource* resource);
private:
	friend class SkeletonLoaderPrivate;

	BlendConverter*		m_file;
	Blender::Object*	m_object;
	bool				m_convAnim;

};
}

#endif//_OgreSkeletonLoader_h_
