/*
-------------------------------------------------------------------------------
	This file is part of OgreKit.
	http://gamekit.googlecode.com/

	Copyright (c) 2009 Charlie C.
-------------------------------------------------------------------------------
 This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
	 claim that you wrote the original software. If you use this software
	 in a product, an acknowledgment in the product documentation would be
	 appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
	 misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.
-------------------------------------------------------------------------------
*/
#include "OgreBone.h"
#include "OgreSkeleton.h"
#include "OgreSkeletonManager.h"

#include "OgreSkeletonLoader.h"
#include "OgreBlendConverter.h"
#include "OgreBlenderDefines.h"
#include "OgreLoaderUtils.h"
#include "OgreHashedString.h"
#include "OgreHashTable.h"
#include "OgreMathUtils.h"
#include "OgrePrint.h"

#include "autogenerated/blender.h"
#include "bBlenderFile.h"
#include "bMain.h"

using namespace Ogre;

namespace Ogre 
{

//-----------------------------------------------------------------------------
class SkeletonLoaderPrivate
{
public:
	SkeletonLoaderPrivate(SkeletonLoader *sl);
	~SkeletonLoaderPrivate();


	void convertSkeleton(Skeleton *skel);
	void buildBoneTree(Blender::Bone *cur, Blender::Bone *prev, Ogre::Bone *parent);

	SkeletonLoader *loader;
	Skeleton* skeleton;
	Blender::bArmature *armature;
};

}



//-----------------------------------------------------------------------------
SkeletonLoaderPrivate::SkeletonLoaderPrivate(SkeletonLoader *sl) :
		loader(sl), armature(0)
{
	OGRE_ASSERT(loader);
}

//-----------------------------------------------------------------------------
SkeletonLoaderPrivate::~SkeletonLoaderPrivate()
{
}


//-----------------------------------------------------------------------------
void SkeletonLoaderPrivate::buildBoneTree(Blender::Bone *cur, Blender::Bone *prev, Ogre::Bone *parent)
{
	/// This is the normal resposition
	OGRE_ASSERT(cur);
	OGRE_ASSERT(skeleton);

	Matrix4 parBind= Matrix4::IDENTITY;
	if (prev != 0 && parent != 0)
		parBind = MathUtils::getFromFloatNorm(prev->arm_mat).inverse();

	/// create the ogre bone
	Ogre::Bone *bone = skeleton->createBone(cur->name);
	if (parent)
		parent->addChild(bone);

	Matrix4 bind = parBind * MathUtils::getFromFloatNorm(cur->arm_mat);

	Quaternion rot; Vector3 loc, scl; 
	MathUtils::extractTransformFast(bind, loc, rot, scl);

	bone->setPosition(loc);
	bone->setOrientation(rot);
	bone->setScale(scl);
	bone->setBindingPose();

	Blender::Bone *chi= static_cast<Blender::Bone*>(cur->childbase.first);
	while (chi)
	{
		// recurse
		buildBoneTree(chi, cur, bone);
		chi= chi->next;
	}
}

//-----------------------------------------------------------------------------
void SkeletonLoaderPrivate::convertSkeleton(Skeleton *skel)
{
	OGRE_ASSERT(skel);
	OGRE_ASSERT(loader);
	OGRE_ASSERT(loader->m_object);
	OGRE_ASSERT(loader->m_object->data);

	armature= static_cast<Blender::bArmature *>(loader->m_object->data);
	skeleton= skel;

	// create bone lists && transforms
	Blender::Bone *bone= static_cast<Blender::Bone*>(armature->bonebase.first);
	while (bone)
	{
		// only process root bones
		if (bone->parent == 0)
			buildBoneTree(bone, NULL, NULL);
		bone= bone->next;
	}
}

//-----------------------------------------------------------------------------
SkeletonLoader::SkeletonLoader(BlendConverter *fp, Blender::Object *arma) :
		m_file(fp),
		m_object(arma)
{
	OGRE_ASSERT(m_file);
}

//-----------------------------------------------------------------------------
SkeletonLoader::~SkeletonLoader()
{
}

//-----------------------------------------------------------------------------
void SkeletonLoader::loadResource(Resource* resource)
{
	OGRE_ASSERT(m_file);
	OGRE_ASSERT(m_object);
	OGRE_ASSERT(resource);

	SkeletonLoaderPrivate converter(this);
	converter.convertSkeleton(static_cast<Skeleton*>(resource));
}
