#ifndef __Custom_Config_H_
#define __Custom_Config_H_

#define OGRE_STATIC_LIB

/// XXX FIX-THIS -> Charlie C
#define OGRE_CONFIG_LITTLE_ENDIAN

/// OgreKit default settings
#define OGRE_DOUBLE_PRECISION 0
#define OGRE_MEMORY_ALLOCATOR 4
#define OGRE_CONTAINERS_USE_CUSTOM_MEMORY_ALLOCATOR 1
#define OGRE_STRING_USE_CUSTOM_MEMORY_ALLOCATOR 0
#define OGRE_MEMORY_TRACKER_DEBUG_MODE 0
#define OGRE_MEMORY_TRACKER_RELEASE_MODE 0
#define OGRE_THREAD_SUPPORT 0
#define OGRE_THREAD_PROVIDER 0
#define OGRE_NO_FREEIMAGE 0
#define OGRE_NO_DDS_CODEC 0
#define OGRE_NO_PVRTC_CODEC 1
#define OGRE_NO_ZIP_ARCHIVE 0
#define OGRE_USE_NEW_COMPILERS 1
#define OGRE_USE_BOOST  0

#endif
